package it.polimi.ingsw.GC_04.client.view;

public enum SetRun {

	CHOOSEACTION, SETFURTHERCHECKNEEDEDEFFECT, SETCOUNCILPRIVILEGE,SETREQUESTEDAUTHORIZATIONEFFECTS, SETDISCOUNT,EXCOMMUNICATIONMANAGEMENT 
}
